version: '3.7'
services:
  rustlesearch_api:
    image: rustlesearch_api:latest
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    networks:
      - rustle-host-bridge
    expose:
      - $APP_PORT
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    restart: unless-stopped
    env_file: .env
    networks:
      - rustle-host-bridge
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - $REDIS_PORT

networks:
  rustle-host-bridge:
    driver: bridge
    driver_opts:
      subnet: 10.0.0.0/24
      gateway: 10.0.0.1
