version: '3.7'
services:
  rustlesearch_api:
    image: rustlesearch_api:latest
    build:
      context: .
    container_name: rustlesearch_api
    restart: unless-stopped
    env_file: .env
    expose:
      - $APP_PORT
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms8g -Xmx8g'
      - discovery.type=single-node
      - index.number_of_replicas=0
      - index.refresh_interval=30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:7.1.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
