version: '3.7'

services:
  rustlesearch_dev:
    image: node:12-alpine
    volumes:
      - .:/node_app
    working_dir: /node_app
    command: yarn start:api
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=${DOMAIN}
    expose:
      - ${APP_PORT}
    depends_on:
      - redis
