version: "3.7"

services:
  rustlesearch_dev:
    image: node:12-alpine
    volumes:
      - .:/node_app
    working_dir: /node_app
    command: tail -F /dev/null
    network_mode: host
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
