version: '3.7'
services:
  rustlesearch_api:
    image: rustlesearch_api:latest
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=api.${DOMAIN}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=api.${DOMAIN}
      - SSL_POLICY=Mozilla-Modern
    expose:
      - ${APP_PORT}
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - $REDIS_PORT

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: rustlesearch-server-nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf:/etc/nginx/conf.d
      - ./config/nginx/vhost:/etc/nginx/vhost.d
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/dhparam:/etc/nginx/dhparam
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: rustlesearch-server-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - ./config/nginx/conf:/etc/nginx/conf.d
      - ./config/nginx/vhost:/etc/nginx/vhost.d
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/dhparam:/etc/nginx/dhparam
      - ./config/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=rustlesearch-server-nginx-proxy
