version: '3.7'
services:
  rustlesearch_api:
    image: rustlesearch_api:latest
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=api.${DOMAIN}
      - RESOLVERS="1.1.1.1 1.0.0.1 valid=300s"
    expose:
      - ${APP_PORT}
    depends_on:
      - redis
  rustlesearch_dev:
    image: node:12
    volumes:
      - .:/node_app
    working_dir: /node_app
    command: echo 1
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=api.${DOMAIN}
      - RESOLVERS="1.1.1.1 1.0.0.1 valid=300s"

    expose:
      - ${APP_PORT}
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - $REDIS_PORT

  nginx-proxy:
    image: nginx:1.17-alpine
    container_name: rustlesearch-server-nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf:/etc/nginx/conf.d
      - ./config/nginx/vhost:/etc/nginx/vhost.d
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/dhparam:/etc/nginx/dhparam
      - ./config/nginx/certs:/etc/nginx/certs:ro
  docker-gen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup rustlesearch-server-nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: rustlesearch-server-nginx-proxy-gen
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - ./config/nginx/conf:/etc/nginx/conf.d
      - ./config/nginx/vhost:/etc/nginx/vhost.d
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - ./config/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: rustlesearch-server-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes:
      - ./config/nginx/vhost:/etc/nginx/vhost.d
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/certs:/etc/nginx/certs
      - ./config/nginx/dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=rustlesearch-server-nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=rustlesearch-server-nginx-proxy-gen
